config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :organizations do
    collection do
      post 'unique_org_name_check'
    end
  end
  devise_for :users
  resources :admins, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/validations/organization.rb
module Validations
  module Organization
    extend ActiveSupport::Concern

    included do
      validates :org_name, presence: true, length: { maximum: 50 }
      validates :org_identifier, presence: true, length: { maximum: 50 }, format: { with: /\A[a-zA-Z0-9_]+\z/ }
      validates :first_name, presence: true, length: {minimum: 2, maximum: 50}
      validates :last_name, presence: true, length: {minimum: 2, maximum: 50}
      validates :addr_line1, presence: true, length: {minimum: 2, maximum: 100}
      validates :addr_line2, length: {maximum: 100}
      validates :city, presence: true, length: {minimum: 2, maximum: 35}
      validates :state, length: { maximum: 50 }
      validates :country, presence: true, length: { maximum: 90 }
      validates :zipcode, presence: true, length: { is: 6 }
    end
  end
end

app/models/concerns/validations/user.rb
module Validations
  module User
    extend ActiveSupport::Concern

    included do
      validates :email, presence: true, uniqueness: true
    end
  end
end

app/models/organization.rb
class Organization < ApplicationRecord
  include Validations::Organization
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

  include Validations::User
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :organization
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  layout 'admin'

  before_action :authenticate_admin

  # GET /admins
  def index
    @organizations = Organization.includes(:user)
  end

  private

  def authenticate_admin
    unless current_user.is_admin
      flash[:notice] = 'You do not have permission to access this page/view.'
      redirect_to root_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Services::Organization
  protect_from_forgery with: :exception

  # This should execute before any other before_action methods
  prepend_before_action :authenticate_user!
end

app/controllers/concerns/services/organization.rb
module Services
  module Organization
    extend ActiveSupport::Concern

    included do
      before_action :org_redirection_method, unless: :devise_controller?
    end

    # Redirect to organization creation page if one not created else to the welcome page.
    def org_redirection_method
      if org_present?
        redirect_to root_path if org_controller?
      else
        redirect_to new_organization_path unless org_controller?
      end
    end

    def org_controller?
      # Any action to organization controller should be prevented if one already created.
      controller_name == "organizations"
    end


    def org_present?(user=current_user)
      user.organization.present?
    end

  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  layout 'postlogin'

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = current_user.build_organization(organization_params)
    respond_to do |format|
      if @organization.save
        format.html { redirect_to root_path, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  def unique_org_name_check
    respond_to do | format |
      format.json { render json: is_org_unique?(params["organization"]["org_name"])}
    end
  end

  private

    def is_org_unique?(org_name)
      Organization.find_by(org_name: org_name).blank?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params.require(:organization).permit(:org_name, :org_identifier, :first_name, :last_name, :addr_line1, :addr_line2, :city, :state, :country, :zipcode, :user_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout 'postlogin'

  def index
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admins/index.html.erb
<div class="row">
  <div class='col-md-12'>
  <table class='table' id='org_list'>
  <thead>
    <th>ID</th>
    <th>Org name</th>
    <th>Org Identifier</th>
    <th>Created_by</th>
    <th>Country</th>
    <th>Created_at</th>
    <th>Updated_at</th>
  </thead>
  <tbody>
    <% @organizations.each do | org | %>
    <tr>
      <td><%=org.id%></td>
      <td><%=org.org_name%></td>
      <td><%=org.org_identifier%></td>
      <td><%=org.user.email%></td>
      <td><%=org.country%></td>
      <td><%=org.created_at%></td>
      <td><%=org.updated_at%></td>
    </tr>
    <% end %>
  </tbody>
  </table>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UpcomingApp</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width" />

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="#">Upcoming App(ADMIN)</a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= link_to "Home", root_path, class: 'nav-link' %>
          </li>

          <li class="nav-item">
            <%= link_to "Logout", destroy_user_session_path, :method => :delete, class: 'nav-link' %>
          </li>

        </ul>
      </div>
    </nav>



    <div class='container' style="padding-top: 4.5em">

      <% if flash.keys.present? %>
      <div class='text-center'>
        <span class="notice"><%= notice %></span>
        <span class="alert"><%= alert %></span>
      </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UpcomingApp</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width" />

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='prelogin-bd'>

    <div class='container'>

      <% if flash.keys.present? %>
      <div class='text-center p-3'>
        <span class="notice"><%= notice %></span>
        <span class="alert"><%= alert %></span>
      </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/postlogin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UpcomingApp</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width" />

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="#">Upcoming App</a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav ml-auto">

          <% if current_user.is_admin %>
            <li class="nav-item">
              <%= link_to "Admin", admins_path, class: 'nav-link' %>
            </li>
          <% end %>


          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "Logout", destroy_user_session_path, :method => :delete, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>



    <div class='container' style="padding-top: 4.5em">

      <% if flash.keys.present? %>
      <div class='text-center'>
        <span class="notice"><%= notice %></span>
        <span class="alert"><%= alert %></span>
      </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/organizations/_form.html.erb
<div class="row">
  <div class='col-md-12'>

  <%= form_for(organization, data: { 'unique-org-url': unique_org_name_check_organizations_path}) do |f| %>
    <div class='row'>
      <div class="col-md-12">
        <% if organization.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

            <ul>
            <% organization.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
      </div>
    </div>


    <div class='row'>
      <div class="col-md-6">
        <div class="form-group">
          <%= f.text_field :org_name, autofocus: true, class:'form-control', placeholder: 'Enter Org Name(req)' %>
        </div>
      </div>

      <div class="col-md-6">
        <div class="form-group">
          <%= f.text_field :first_name, class:'form-control', placeholder: 'First Name(req)'  %>
        </div>
      </div>
    </div>


    <div class='row'>
      <div class="col-md-6">
        <div class="form-group row">
          <label class='col-sm-2 col-form-label'>Org Identifier:</label>
          <div class="col-sm-10">
          <%= f.text_field :org_identifier, class:'form-control', placeholder: 'enter_org_name',:readonly => true  %>
          </div>
        </div>
      </div>

      <div class="col-md-6">
        <div class="form-group">
          <%= f.text_field :last_name, class:'form-control', placeholder: 'Last Name(req)'  %>
        </div>
      </div>
    </div>

    <div class='row'>
      <div class="col-md-6 offset-md-3">
        <div class="form-group">
          <%= f.text_field :addr_line1, class:'form-control', placeholder: 'Line 1(req)'  %>
        </div>
      </div>
    </div>

    <div class='row'>
      <div class="col-md-6 offset-md-3">
        <div class="form-group">
          <%= f.text_field :addr_line2, class:'form-control', placeholder: 'Line 2'  %>
        </div>
      </div>
    </div>


    <div class='row'>
    <div class="col-md-6 offset-md-3">
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <%= f.text_field :city, class:'form-control', placeholder: 'City(req)'  %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <%= f.text_field :state, class:'form-control', placeholder: 'State'  %>
          </div>
        </div>
      </div>
    </div>
    </div>

    <div class='row'>
    <div class="col-md-6 offset-md-3">
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <%= f.text_field :country, class:'form-control', placeholder: 'Country(req)'  %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <%= f.number_field :zipcode, class:'form-control', placeholder: 'ZipCode(req)'  %>
          </div>
        </div>
      </div>
    </div>
    </div>
    <div class="col-md-12 text-center">
      <div class="form-group">
        <%= f.submit class: 'btn btn-primary' %>
        <%= link_to 'Back', organizations_path, class: 'btn btn-info' %>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/organizations/new.html.erb
<h1>New Organization</h1>

<%= render 'form', organization: @organization %>

app/views/welcome/index.html.erb
<h3>Thank you for registering.</h3>
<h3>We'll let you know once our product is ready</h3>